export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const LOGOUT = 'LOGOUT';
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_FEED_PROFILE = 'FETCH_FEED_PROFILE';
export const FETCH_FEED_PUBLICATIONS = 'FETCH_FEED_PUBLICATIONS';
export const LIKE_FEED_PUBLICATIONS = 'LIKE_FEED_PUBLICATIONS';
export const LIKE_FEED_PROFILE = 'LIKE_FEED_PROFILE';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';
export const DELETE_POST = 'DELETE_POST';
export const ADD_USER = 'ADD_USER';
export const ADD_FILTER_SUCCESS='ADD_FILTER_SUCCESS'